# Generated by Django 5.1.15 on 2026-05-11 18:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProviderListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider_tenant_id', models.CharField(max_length=120, verbose_name='provider tenant ID')),
                ('listing_type', models.CharField(choices=[('service', 'Service'), ('subscription', 'Subscription'), ('product', 'Product')], max_length=16, verbose_name='listing type')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('paused', 'Paused'), ('archived', 'Archived')], default='draft', max_length=16, verbose_name='status')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('short_description', models.CharField(blank=True, max_length=255, verbose_name='short description')),
                ('category', models.CharField(blank=True, max_length=64, verbose_name='category')),
                ('tags', models.JSONField(blank=True, default=list, verbose_name='tags')),
                ('pricing_model', models.CharField(choices=[('fixed', 'Fixed'), ('monthly', 'Monthly'), ('yearly', 'Yearly'), ('usage_based', 'Usage based')], max_length=16, verbose_name='pricing model')),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='base price')),
                ('currency', models.CharField(default='EUR', max_length=3, verbose_name='currency')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='metadata')),
                ('is_public', models.BooleanField(default=True, verbose_name='public')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
            options={
                'verbose_name': 'provider listing',
                'verbose_name_plural': 'provider listings',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['provider_tenant_id', 'status'], name='marketplace_provide_842622_idx'), models.Index(fields=['category', 'status'], name='marketplace_categor_118bf4_idx')],
            },
        ),
        migrations.CreateModel(
            name='MarketplaceOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_tenant_id', models.CharField(max_length=120, verbose_name='owner tenant ID')),
                ('provider_tenant_id', models.CharField(max_length=120, verbose_name='provider tenant ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], default='pending', max_length=16, verbose_name='status')),
                ('offered_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='offered price')),
                ('currency', models.CharField(default='EUR', max_length=3, verbose_name='currency')),
                ('message', models.TextField(blank=True, verbose_name='message')),
                ('valid_until', models.DateTimeField(blank=True, null=True, verbose_name='valid until')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('responded_at', models.DateTimeField(blank=True, null=True, verbose_name='responded at')),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='marketplace.providerlisting', verbose_name='listing')),
            ],
            options={
                'verbose_name': 'marketplace offer',
                'verbose_name_plural': 'marketplace offers',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProviderListingMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_type', models.CharField(choices=[('image', 'Image'), ('document', 'Document')], max_length=16, verbose_name='media type')),
                ('file_url', models.URLField(max_length=512, verbose_name='file URL')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='sort order')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='marketplace.providerlisting', verbose_name='listing')),
            ],
            options={
                'verbose_name': 'provider listing media',
                'verbose_name_plural': 'provider listing media',
                'ordering': ['listing', 'sort_order'],
            },
        ),
        migrations.CreateModel(
            name='ProviderServiceArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=4, verbose_name='country')),
                ('city', models.CharField(blank=True, max_length=120, null=True, verbose_name='city')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_areas', to='marketplace.providerlisting', verbose_name='listing')),
            ],
            options={
                'verbose_name': 'provider service area',
                'verbose_name_plural': 'provider service areas',
            },
        ),
        migrations.CreateModel(
            name='ServiceOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_tenant_id', models.CharField(max_length=120, verbose_name='owner tenant ID')),
                ('provider_tenant_id', models.CharField(max_length=120, verbose_name='provider tenant ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('in_progress', 'In progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=16, verbose_name='status')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='total amount')),
                ('currency', models.CharField(default='EUR', max_length=3, verbose_name='currency')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='metadata')),
                ('ordered_at', models.DateTimeField(auto_now_add=True, verbose_name='ordered at')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='completed at')),
                ('listing', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='marketplace.providerlisting', verbose_name='listing')),
                ('marketplace_offer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='marketplace.marketplaceoffer', verbose_name='marketplace offer')),
            ],
            options={
                'verbose_name': 'service order',
                'verbose_name_plural': 'service orders',
                'ordering': ['-ordered_at'],
            },
        ),
        migrations.AddIndex(
            model_name='marketplaceoffer',
            index=models.Index(fields=['owner_tenant_id', 'status'], name='marketplace_owner_t_c804da_idx'),
        ),
        migrations.AddIndex(
            model_name='marketplaceoffer',
            index=models.Index(fields=['listing', 'status'], name='marketplace_listing_e1c337_idx'),
        ),
        migrations.AddConstraint(
            model_name='providerservicearea',
            constraint=models.UniqueConstraint(fields=('listing', 'country', 'city'), name='unique_listing_area'),
        ),
        migrations.AddIndex(
            model_name='serviceorder',
            index=models.Index(fields=['owner_tenant_id', 'status'], name='marketplace_owner_t_50db56_idx'),
        ),
        migrations.AddIndex(
            model_name='serviceorder',
            index=models.Index(fields=['provider_tenant_id', 'status'], name='marketplace_provide_672730_idx'),
        ),
    ]
