# Generated by Django 5.1.15 on 2026-05-11 14:00

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0002_device_activated_at_device_provisioned_at'),
        ('notifications', '0001_initial'),
        ('plants', '0001_initial'),
        ('telemetry', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alert',
            options={'ordering': ['-first_seen_at'], 'verbose_name': 'alert', 'verbose_name_plural': 'alerts'},
        ),
        migrations.AddField(
            model_name='alert',
            name='acknowledged_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='acknowledged at'),
        ),
        migrations.AddField(
            model_name='alert',
            name='alert_key',
            field=models.CharField(blank=True, default='', help_text='Deduplication key: unique while status is open/acknowledged. Blank default exists only for legacy migration safety; runtime values are always set by the service layer.', max_length=255, verbose_name='alert key'),
        ),
        migrations.AddField(
            model_name='alert',
            name='device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alerts', to='devices.device', verbose_name='device'),
        ),
        migrations.AddField(
            model_name='alert',
            name='dismissed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='dismissed at'),
        ),
        migrations.AddField(
            model_name='alert',
            name='first_seen_at',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Default is timezone.now for migration safety; runtime values are always set by the service layer.', verbose_name='first seen at'),
        ),
        migrations.AddField(
            model_name='alert',
            name='last_seen_at',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Default is timezone.now for migration safety; runtime values are always set by the service layer.', verbose_name='last seen at'),
        ),
        migrations.AddField(
            model_name='alert',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, verbose_name='metadata'),
        ),
        migrations.AddField(
            model_name='alert',
            name='plant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alerts', to='plants.plant', verbose_name='plant'),
        ),
        migrations.AddField(
            model_name='alert',
            name='resolved_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='resolved at'),
        ),
        migrations.AddField(
            model_name='alert',
            name='rule_code',
            field=models.CharField(blank=True, default='', help_text='Identifier of the rule that triggered this alert.', max_length=64, verbose_name='rule code'),
        ),
        migrations.AddField(
            model_name='alert',
            name='sensor_reading',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alerts', to='telemetry.sensorreading', verbose_name='sensor reading'),
        ),
        migrations.AddField(
            model_name='alert',
            name='source_id',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='source ID'),
        ),
        migrations.AddField(
            model_name='alert',
            name='source_type',
            field=models.CharField(choices=[('sensor_reading', 'Sensor reading'), ('device', 'Device'), ('plant', 'Plant'), ('system', 'System')], default='sensor_reading', max_length=32, verbose_name='source type'),
        ),
        migrations.AlterField(
            model_name='alert',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('acknowledged', 'Acknowledged'), ('resolved', 'Resolved'), ('dismissed', 'Dismissed')], default='open', max_length=32, verbose_name='status'),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['alert_key', 'status'], name='notificatio_alert_k_1d5932_idx'),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['rule_code', 'status'], name='notificatio_rule_co_83e0cb_idx'),
        ),
    ]
