# Generated by Django 5.1.15 on 2026-05-11 14:16

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_alter_alert_options_alert_acknowledged_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationOutbox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Stable idempotency key for deduplication.', unique=True, verbose_name='event ID')),
                ('notification_type', models.CharField(choices=[('alert_created', 'Alert created'), ('alert_updated', 'Alert updated'), ('alert_resolved', 'Alert resolved')], max_length=32, verbose_name='notification type')),
                ('channel', models.CharField(choices=[('push', 'Push'), ('email', 'Email'), ('sms', 'SMS'), ('in_app', 'In-app'), ('webhook', 'Webhook')], default='in_app', max_length=16, verbose_name='channel')),
                ('recipient_type', models.CharField(choices=[('user', 'User'), ('tenant', 'Tenant'), ('provider', 'Provider'), ('system', 'System')], default='tenant', max_length=16, verbose_name='recipient type')),
                ('recipient_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='recipient ID')),
                ('payload', models.JSONField(blank=True, default=dict, verbose_name='payload')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('sent', 'Sent'), ('retry', 'Retry'), ('failed', 'Failed'), ('dead_letter', 'Dead letter')], default='pending', max_length=16, verbose_name='status')),
                ('attempt_count', models.PositiveIntegerField(default=0, verbose_name='attempt count')),
                ('available_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='available at')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='sent at')),
                ('failed_at', models.DateTimeField(blank=True, null=True, verbose_name='failed at')),
                ('last_error', models.TextField(blank=True, verbose_name='last error')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('alert', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notification_outbox', to='notifications.alert', verbose_name='alert')),
            ],
            options={
                'verbose_name': 'notification outbox',
                'verbose_name_plural': 'notification outboxes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempt_number', models.PositiveIntegerField(verbose_name='attempt number')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('sent', 'Sent'), ('retry', 'Retry'), ('failed', 'Failed'), ('dead_letter', 'Dead letter')], max_length=16, verbose_name='status')),
                ('channel', models.CharField(choices=[('push', 'Push'), ('email', 'Email'), ('sms', 'SMS'), ('in_app', 'In-app'), ('webhook', 'Webhook')], max_length=16, verbose_name='channel')),
                ('error', models.TextField(blank=True, verbose_name='error')),
                ('provider_response', models.JSONField(blank=True, default=dict, verbose_name='provider response')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='notifications.notificationoutbox', verbose_name='notification')),
            ],
            options={
                'verbose_name': 'notification delivery',
                'verbose_name_plural': 'notification deliveries',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_type', models.CharField(choices=[('user', 'User'), ('tenant', 'Tenant'), ('provider', 'Provider'), ('system', 'System')], max_length=16, verbose_name='recipient type')),
                ('recipient_id', models.CharField(max_length=255, verbose_name='recipient ID')),
                ('channel', models.CharField(choices=[('push', 'Push'), ('email', 'Email'), ('sms', 'SMS'), ('in_app', 'In-app'), ('webhook', 'Webhook')], max_length=16, verbose_name='channel')),
                ('enabled', models.BooleanField(default=True, verbose_name='enabled')),
                ('alert_severity_min', models.CharField(blank=True, default='info', help_text='Only deliver alerts at this severity or higher.', max_length=16, verbose_name='minimum alert severity')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
            options={
                'verbose_name': 'notification preference',
                'verbose_name_plural': 'notification preferences',
                'constraints': [models.UniqueConstraint(fields=('recipient_type', 'recipient_id', 'channel'), name='unique_recipient_channel_preference')],
            },
        ),
        migrations.AddIndex(
            model_name='notificationoutbox',
            index=models.Index(fields=['status', 'available_at'], name='notificatio_status_a0e682_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationoutbox',
            index=models.Index(fields=['notification_type', 'status'], name='notificatio_notific_5f0d13_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationdelivery',
            index=models.Index(fields=['notification', 'attempt_number'], name='notificatio_notific_e24ea1_idx'),
        ),
    ]
