# Generated by Django 5.1.15 on 2026-05-11 15:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_notificationoutbox_notificationdelivery_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DevicePushToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.CharField(max_length=120, verbose_name='tenant ID')),
                ('provider_type', models.CharField(choices=[('fcm', 'FCM'), ('apns', 'APNs')], max_length=8, verbose_name='provider type')),
                ('token', models.CharField(max_length=512, unique=True, verbose_name='token')),
                ('platform', models.CharField(choices=[('android', 'Android'), ('ios', 'iOS'), ('web', 'Web')], default='android', max_length=16, verbose_name='platform')),
                ('app_version', models.CharField(blank=True, max_length=32, null=True, verbose_name='app version')),
                ('device_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='device name')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('last_seen_at', models.DateTimeField(auto_now=True, verbose_name='last seen at')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='push_tokens', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'device push token',
                'verbose_name_plural': 'device push tokens',
                'ordering': ['-last_seen_at'],
                'indexes': [models.Index(fields=['tenant_id', 'is_active'], name='notificatio_tenant__8dae48_idx'), models.Index(fields=['provider_type', 'is_active'], name='notificatio_provide_3f8dee_idx')],
            },
        ),
        migrations.CreateModel(
            name='EmailDestination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.CharField(max_length=120, verbose_name='tenant ID')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('is_verified', models.BooleanField(default=False, verbose_name='verified')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='email_destinations', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'email destination',
                'verbose_name_plural': 'email destinations',
                'ordering': ['email'],
                'constraints': [models.UniqueConstraint(fields=('tenant_id', 'email'), name='unique_tenant_email_destination')],
            },
        ),
    ]
