# Generated by Django 5.1.15 on 2026-05-12 03:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_devicepushtoken_emaildestination'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('acknowledged', 'Acknowledged'), ('resolved', 'Resolved'), ('dismissed', 'Dismissed'), ('escalated', 'Escalated')], max_length=32, verbose_name='event type')),
                ('from_status', models.CharField(blank=True, default='', max_length=32, verbose_name='from status')),
                ('to_status', models.CharField(max_length=32, verbose_name='to status')),
                ('triggered_by', models.CharField(blank=True, default='', help_text='Service, user, or system that triggered this event.', max_length=255, verbose_name='triggered by')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='metadata')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('alert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='notifications.alert', verbose_name='alert')),
            ],
            options={
                'verbose_name': 'alert event',
                'verbose_name_plural': 'alert events',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['alert', '-created_at'], name='notificatio_alert_i_b920aa_idx'), models.Index(fields=['event_type', '-created_at'], name='notificatio_event_t_0f5e89_idx')],
            },
        ),
    ]
