# Generated by Django 5.1.15 on 2026-05-12 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0005_alertevent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('acknowledged', 'Acknowledged'), ('resolved', 'Resolved'), ('dismissed', 'Dismissed'), ('suppressed', 'Suppressed')], default='open', max_length=32, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='alertevent',
            name='event_type',
            field=models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('acknowledged', 'Acknowledged'), ('resolved', 'Resolved'), ('dismissed', 'Dismissed'), ('escalated', 'Escalated'), ('suppressed', 'Suppressed')], max_length=32, verbose_name='event type'),
        ),
    ]
