# Generated by Django 5.1.15 on 2026-05-14 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0006_alter_alert_status_alter_alertevent_event_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='first_triggered_at',
            field=models.DateTimeField(blank=True, help_text='When the alert was first created. Re-opens do NOT change this.', null=True, verbose_name='first triggered at'),
        ),
        migrations.AddField(
            model_name='alert',
            name='trigger_count',
            field=models.PositiveIntegerField(default=1, help_text='How many times this alert has been triggered (re-opened after cooldown).', verbose_name='trigger count'),
        ),
    ]
