# Generated by Django 5.1.15 on 2026-05-14 10:42

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('devices', '0005_devicedomainevent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('name', models.CharField(max_length=100, verbose_name='rule name')),
                ('sensor_type', models.CharField(max_length=64, verbose_name='sensor type')),
                ('condition', models.CharField(choices=[('lt', 'Less Than'), ('gt', 'Greater Than'), ('lte', 'Less Than or Equal'), ('gte', 'Greater Than or Equal'), ('eq', 'Equal')], help_text='Comparison operator for the threshold.', max_length=5, verbose_name='condition')),
                ('threshold', models.FloatField(help_text='Value to compare against.', verbose_name='threshold')),
                ('duration_minutes', models.PositiveIntegerField(default=0, help_text='How long the condition must persist before triggering. 0 = immediate.', verbose_name='duration (minutes)')),
                ('severity', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('critical', 'Critical')], default='warning', max_length=20, verbose_name='severity')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='updated by')),
            ],
            options={
                'verbose_name': 'alert rule',
                'verbose_name_plural': 'alert rules',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('severity', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('critical', 'Critical')], default='warning', max_length=20, verbose_name='severity')),
                ('message', models.TextField(verbose_name='message')),
                ('value', models.FloatField(blank=True, null=True, verbose_name='triggering value')),
                ('threshold', models.FloatField(blank=True, null=True, verbose_name='threshold value')),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True, verbose_name='acknowledged at')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='resolved at')),
                ('is_active', models.BooleanField(default=True, help_text='False once the alert is resolved.', verbose_name='active')),
                ('acknowledged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acknowledged_alerts', to=settings.AUTH_USER_MODEL, verbose_name='acknowledged by')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rule_alerts', to='devices.device', verbose_name='device')),
                ('rule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alerts', to='alerts.alertrule', verbose_name='rule')),
            ],
            options={
                'verbose_name': 'alert',
                'verbose_name_plural': 'alerts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AlertEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('event_type', models.CharField(choices=[('triggered', 'Triggered'), ('acknowledged', 'Acknowledged'), ('resolved', 'Resolved'), ('auto_resolved', 'Auto-Resolved')], max_length=20, verbose_name='event type')),
                ('details', models.JSONField(default=dict, verbose_name='details')),
                ('occurred_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='occurred at')),
                ('actor', models.ForeignKey(blank=True, help_text='User who performed the action, if applicable.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alert_events', to=settings.AUTH_USER_MODEL, verbose_name='actor')),
                ('alert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='alerts.alert', verbose_name='alert')),
            ],
            options={
                'verbose_name': 'alert event',
                'verbose_name_plural': 'alert events',
                'ordering': ['-occurred_at'],
                'indexes': [models.Index(fields=['alert', 'occurred_at'], name='alerts_aler_alert_i_15c2c0_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='alertrule',
            index=models.Index(fields=['sensor_type', 'is_active'], name='alerts_aler_sensor__64db0f_idx'),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['device', 'is_active'], name='alerts_aler_device__8c178d_idx'),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['severity', 'is_active'], name='alerts_aler_severit_72b37d_idx'),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['is_active', 'created_at'], name='alerts_aler_is_acti_2b2b44_idx'),
        ),
    ]
