# Generated by Django 5.1.15 on 2026-05-11 08:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SensorReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('measured_at', models.DateTimeField(db_index=True, verbose_name='measured at')),
                ('soil_moisture', models.FloatField(blank=True, null=True, verbose_name='soil moisture')),
                ('temperature', models.FloatField(blank=True, null=True, verbose_name='temperature')),
                ('air_humidity', models.FloatField(blank=True, null=True, verbose_name='air humidity')),
                ('light_level', models.FloatField(blank=True, null=True, verbose_name='light level')),
                ('battery_level', models.FloatField(blank=True, null=True, verbose_name='battery level')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sensor_readings', to='devices.device', verbose_name='device')),
            ],
            options={
                'verbose_name': 'sensor reading',
                'verbose_name_plural': 'sensor readings',
                'ordering': ['-measured_at'],
                'indexes': [models.Index(fields=['device', 'measured_at'], name='telemetry_s_device__68232c_idx')],
            },
        ),
    ]
