# Generated by Django 5.1.15 on 2026-05-11 09:58

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='B2BIdempotencyKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=255, verbose_name='key')),
                ('endpoint', models.CharField(max_length=255, verbose_name='endpoint')),
                ('request_hash', models.CharField(max_length=64, verbose_name='request hash')),
                ('response_status', models.PositiveIntegerField(verbose_name='response status')),
                ('response_body', models.JSONField(default=dict, verbose_name='response body')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
            ],
            options={
                'verbose_name': 'B2B idempotency key',
                'verbose_name_plural': 'B2B idempotency keys',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['key', 'endpoint'], name='provider_op_key_8428f2_idx')],
                'constraints': [models.UniqueConstraint(fields=('key', 'endpoint'), name='provider_b2b_idempotency_key_endpoint_uniq')],
            },
        ),
        migrations.CreateModel(
            name='ExternalLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_owner_tenant_id', models.CharField(max_length=120, verbose_name='source owner tenant ID')),
                ('external_id', models.CharField(max_length=120, verbose_name='external ID')),
                ('name', models.CharField(max_length=180, verbose_name='name')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='address')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='latitude')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='longitude')),
                ('raw_payload', models.JSONField(blank=True, default=dict, verbose_name='raw payload')),
                ('last_synced_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='last synced at')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
            options={
                'verbose_name': 'external location',
                'verbose_name_plural': 'external locations',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['source_owner_tenant_id', 'external_id'], name='provider_op_source__b96dde_idx')],
                'constraints': [models.UniqueConstraint(fields=('source_owner_tenant_id', 'external_id'), name='provider_external_location_source_external_uniq')],
            },
        ),
        migrations.CreateModel(
            name='ExternalDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_owner_tenant_id', models.CharField(max_length=120, verbose_name='source owner tenant ID')),
                ('external_id', models.CharField(max_length=120, verbose_name='external ID')),
                ('name', models.CharField(max_length=180, verbose_name='name')),
                ('status', models.CharField(max_length=64, verbose_name='status')),
                ('raw_payload', models.JSONField(blank=True, default=dict, verbose_name='raw payload')),
                ('last_synced_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='last synced at')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('external_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='external_devices', to='provider_ops.externallocation', verbose_name='external location')),
            ],
            options={
                'verbose_name': 'external device',
                'verbose_name_plural': 'external devices',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TelemetryIngest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_owner_tenant_id', models.CharField(max_length=120, verbose_name='source owner tenant ID')),
                ('external_reading_id', models.CharField(max_length=120, verbose_name='external reading ID')),
                ('measured_at', models.DateTimeField(verbose_name='measured at')),
                ('soil_moisture', models.FloatField(blank=True, null=True, verbose_name='soil moisture')),
                ('temperature', models.FloatField(blank=True, null=True, verbose_name='temperature')),
                ('air_humidity', models.FloatField(blank=True, null=True, verbose_name='air humidity')),
                ('light_level', models.FloatField(blank=True, null=True, verbose_name='light level')),
                ('battery_level', models.FloatField(blank=True, null=True, verbose_name='battery level')),
                ('raw_payload', models.JSONField(blank=True, default=dict, verbose_name='raw payload')),
                ('received_at', models.DateTimeField(auto_now_add=True, verbose_name='received at')),
                ('external_device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telemetry_ingests', to='provider_ops.externaldevice', verbose_name='external device')),
            ],
            options={
                'verbose_name': 'telemetry ingest',
                'verbose_name_plural': 'telemetry ingests',
                'ordering': ['-measured_at'],
            },
        ),
        migrations.AddIndex(
            model_name='externaldevice',
            index=models.Index(fields=['source_owner_tenant_id', 'external_id'], name='provider_op_source__efaec7_idx'),
        ),
        migrations.AddConstraint(
            model_name='externaldevice',
            constraint=models.UniqueConstraint(fields=('source_owner_tenant_id', 'external_id'), name='provider_external_device_source_external_uniq'),
        ),
        migrations.AddIndex(
            model_name='telemetryingest',
            index=models.Index(fields=['source_owner_tenant_id', 'external_reading_id'], name='provider_op_source__ab3cfe_idx'),
        ),
        migrations.AddIndex(
            model_name='telemetryingest',
            index=models.Index(fields=['external_device', 'measured_at'], name='provider_op_externa_94e8b2_idx'),
        ),
        migrations.AddConstraint(
            model_name='telemetryingest',
            constraint=models.UniqueConstraint(fields=('source_owner_tenant_id', 'external_reading_id'), name='provider_telemetry_source_reading_uniq'),
        ),
    ]
