# Generated by Django 5.1.15 on 2026-05-11 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provider_ops', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProviderInboundKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key_id', models.CharField(help_text='Public identifier sent in the X-B2B-Key-Id header.', max_length=120, unique=True, verbose_name='key ID')),
                ('source_owner_tenant_id', models.CharField(help_text='The owner tenant that this key authenticates requests from.', max_length=120, verbose_name='source owner tenant ID')),
                ('secret_reference', models.CharField(help_text='Reference to a secret resolver entry; never store the plain secret here.', max_length=255, verbose_name='secret reference')),
                ('status', models.CharField(choices=[('active', 'Active'), ('disabled', 'Disabled'), ('revoked', 'Revoked')], default='active', max_length=32, verbose_name='status')),
                ('valid_from', models.DateTimeField(verbose_name='valid from')),
                ('valid_until', models.DateTimeField(blank=True, null=True, verbose_name='valid until')),
                ('scopes', models.JSONField(blank=True, default=list, help_text='Allowed endpoint scopes for this key (e.g. telemetry:write).', verbose_name='scopes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('revoked_at', models.DateTimeField(blank=True, null=True, verbose_name='revoked at')),
            ],
            options={
                'verbose_name': 'provider inbound key',
                'verbose_name_plural': 'provider inbound keys',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['key_id', 'status'], name='provider_op_key_id_b6a77f_idx'), models.Index(fields=['source_owner_tenant_id', 'status'], name='provider_op_source__ddef42_idx')],
            },
        ),
    ]
