# Generated by Django 5.1.15 on 2026-05-11 16:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provider_ops', '0002_providerinboundkey'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProviderTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_key', models.CharField(help_text='Idempotency key — same task_key never creates a duplicate.', max_length=255, unique=True, verbose_name='task key')),
                ('source_owner_tenant_id', models.CharField(max_length=120, verbose_name='source owner tenant ID')),
                ('external_alert_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='external alert ID')),
                ('external_location_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='external location ID')),
                ('external_plant_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='external plant ID')),
                ('external_device_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='external device ID')),
                ('task_type', models.CharField(choices=[('inspection', 'Inspection'), ('watering', 'Watering'), ('device_check', 'Device check'), ('replacement', 'Replacement'), ('maintenance', 'Maintenance'), ('other', 'Other')], max_length=32, verbose_name='task type')),
                ('priority', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('urgent', 'Urgent')], default='normal', max_length=16, verbose_name='priority')),
                ('status', models.CharField(choices=[('open', 'Open'), ('assigned', 'Assigned'), ('in_progress', 'In progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='open', max_length=16, verbose_name='status')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('assignee_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='assignee ID')),
                ('due_at', models.DateTimeField(blank=True, null=True, verbose_name='due at')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='started at')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='completed at')),
                ('cancelled_at', models.DateTimeField(blank=True, null=True, verbose_name='cancelled at')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='metadata')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
            options={
                'verbose_name': 'provider task',
                'verbose_name_plural': 'provider tasks',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'priority'], name='provider_op_status_6f2eb7_idx'), models.Index(fields=['task_type', 'status'], name='provider_op_task_ty_009c57_idx'), models.Index(fields=['assignee_id', 'status'], name='provider_op_assigne_b0ff80_idx'), models.Index(fields=['due_at'], name='provider_op_due_at_8fa919_idx')],
            },
        ),
        migrations.CreateModel(
            name='ProviderTaskEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('created', 'Created'), ('assigned', 'Assigned'), ('started', 'Started'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('note_added', 'Note added')], max_length=32, verbose_name='event type')),
                ('actor_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='actor ID')),
                ('message', models.TextField(blank=True, verbose_name='message')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='metadata')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='provider_ops.providertask', verbose_name='task')),
            ],
            options={
                'verbose_name': 'provider task event',
                'verbose_name_plural': 'provider task events',
                'ordering': ['task', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProviderTaskNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='actor ID')),
                ('body', models.TextField(verbose_name='body')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='provider_ops.providertask', verbose_name='task')),
            ],
            options={
                'verbose_name': 'provider task note',
                'verbose_name_plural': 'provider task notes',
                'ordering': ['task', '-created_at'],
            },
        ),
    ]
