# Generated by Django 5.1.15 on 2026-05-11 16:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provider_ops', '0003_providertask_providertaskevent_providertasknote'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskEscalationEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('escalation_type', models.CharField(choices=[('response_sla_breach', 'Response SLA breach'), ('resolution_sla_breach', 'Resolution SLA breach'), ('overdue', 'Overdue'), ('reassignment', 'Reassignment'), ('priority_upgrade', 'Priority upgrade'), ('reminder_sent', 'Reminder sent')], max_length=32, verbose_name='escalation type')),
                ('previous_priority', models.CharField(blank=True, max_length=16, null=True, verbose_name='previous priority')),
                ('new_priority', models.CharField(blank=True, max_length=16, null=True, verbose_name='new priority')),
                ('previous_assignee', models.CharField(blank=True, max_length=255, null=True, verbose_name='previous assignee')),
                ('new_assignee', models.CharField(blank=True, max_length=255, null=True, verbose_name='new assignee')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='metadata')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='escalation_events', to='provider_ops.providertask', verbose_name='task')),
            ],
            options={
                'verbose_name': 'task escalation event',
                'verbose_name_plural': 'task escalation events',
                'ordering': ['task', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TaskSLA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response_due_at', models.DateTimeField(blank=True, null=True, verbose_name='response due at')),
                ('resolution_due_at', models.DateTimeField(blank=True, null=True, verbose_name='resolution due at')),
                ('first_assigned_at', models.DateTimeField(blank=True, null=True, verbose_name='first assigned at')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='resolved at')),
                ('breached_response_sla', models.BooleanField(default=False, verbose_name='breached response SLA')),
                ('breached_resolution_sla', models.BooleanField(default=False, verbose_name='breached resolution SLA')),
                ('escalation_level', models.PositiveIntegerField(default=0, verbose_name='escalation level')),
                ('last_escalated_at', models.DateTimeField(blank=True, null=True, verbose_name='last escalated at')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('task', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sla', to='provider_ops.providertask', verbose_name='task')),
            ],
            options={
                'verbose_name': 'task SLA',
                'verbose_name_plural': 'task SLAs',
                'indexes': [models.Index(fields=['breached_response_sla', 'breached_resolution_sla'], name='provider_op_breache_95f336_idx'), models.Index(fields=['escalation_level'], name='provider_op_escalat_113350_idx')],
            },
        ),
    ]
