# Generated by Django 5.1.15 on 2026-05-11 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provider_ops', '0004_taskescalationevent_tasksla'),
    ]

    operations = [
        migrations.CreateModel(
            name='RealtimeEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_schema', models.CharField(max_length=120, verbose_name='tenant schema')),
                ('event_type', models.CharField(max_length=64, verbose_name='event type')),
                ('entity_type', models.CharField(max_length=64, verbose_name='entity type')),
                ('entity_id', models.CharField(max_length=255, verbose_name='entity ID')),
                ('version', models.PositiveIntegerField(default=1, verbose_name='version')),
                ('payload', models.JSONField(blank=True, default=dict, verbose_name='payload')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
            ],
            options={
                'verbose_name': 'realtime event',
                'verbose_name_plural': 'realtime events',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['tenant_schema', '-created_at'], name='provider_op_tenant__e9f181_idx'), models.Index(fields=['entity_type', 'entity_id'], name='provider_op_entity__88e240_idx')],
            },
        ),
    ]
