# Generated by Django 5.1.15 on 2026-05-11 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('sync', 'Sync'), ('security', 'Security')], max_length=32, verbose_name='action')),
                ('target_type', models.CharField(max_length=120, verbose_name='target type')),
                ('target_id', models.CharField(max_length=120, verbose_name='target ID')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='metadata')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
            ],
            options={
                'verbose_name': 'audit log',
                'verbose_name_plural': 'audit logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
