"""
Tasks bounded context.

Responsible for tasks generated by the system or created manually.
Examples: water plant, check device, replace battery.
"""

from django.conf import settings
from django.db import models
from django.utils.translation import gettext_lazy as _

from apps.core.models import AuditableModel


class Task(AuditableModel):
    """
    A task that needs to be performed.

    Can be created manually by users or automatically by the
    automation engine in response to alerts or thresholds.
    """

    class TaskType(models.TextChoices):
        WATER = "water", _("Water Plant")
        CHECK_DEVICE = "check_device", _("Check Device")
        REPLACE_BATTERY = "replace_battery", _("Replace Battery")
        PRUNE = "prune", _("Prune")
        REPOT = "repot", _("Repot")
        FERTILIZE = "fertilize", _("Fertilize")
        MOVE = "move", _("Move Plant")
        OTHER = "other", _("Other")

    class Status(models.TextChoices):
        OPEN = "open", _("Open")
        IN_PROGRESS = "in_progress", _("In Progress")
        COMPLETED = "completed", _("Completed")
        CANCELLED = "cancelled", _("Cancelled")

    class Priority(models.TextChoices):
        LOW = "low", _("Low")
        MEDIUM = "medium", _("Medium")
        HIGH = "high", _("High")
        URGENT = "urgent", _("Urgent")

    class Source(models.TextChoices):
        MANUAL = "manual", _("Manual")
        AUTOMATION = "automation", _("Automation")
        ALERT = "alert", _("Alert")

    title = models.CharField(
        max_length=200,
        verbose_name=_("title"),
    )
    description = models.TextField(
        blank=True,
        verbose_name=_("description"),
    )
    task_type = models.CharField(
        max_length=20,
        choices=TaskType.choices,
        default=TaskType.OTHER,
        verbose_name=_("task type"),
    )
    status = models.CharField(
        max_length=20,
        choices=Status.choices,
        default=Status.OPEN,
        verbose_name=_("status"),
        db_index=True,
    )
    priority = models.CharField(
        max_length=10,
        choices=Priority.choices,
        default=Priority.MEDIUM,
        verbose_name=_("priority"),
    )
    plant = models.ForeignKey(
        "plants.Plant",
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name="tasks",
        verbose_name=_("plant"),
    )
    device = models.ForeignKey(
        "devices.Device",
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name="tasks",
        verbose_name=_("device"),
    )
    planter = models.ForeignKey(
        "planters.Planter",
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name="tasks",
        verbose_name=_("planter"),
    )
    location = models.ForeignKey(
        "locations.Location",
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name="tasks",
        verbose_name=_("location"),
    )
    assigned_to = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name="assigned_tasks",
        verbose_name=_("assigned to"),
    )
    due_date = models.DateTimeField(
        null=True,
        blank=True,
        verbose_name=_("due date"),
    )
    completed_at = models.DateTimeField(
        null=True,
        blank=True,
        verbose_name=_("completed at"),
    )
    source = models.CharField(
        max_length=20,
        choices=Source.choices,
        default=Source.MANUAL,
        verbose_name=_("source"),
        help_text=_("How this task was created."),
    )

    class Meta:
        verbose_name = _("task")
        verbose_name_plural = _("tasks")
        ordering = ["-priority", "-created_at"]
        indexes = [
            models.Index(fields=["status", "priority"]),
            models.Index(fields=["assigned_to", "status"]),
            models.Index(fields=["due_date"]),
        ]

    def __str__(self) -> str:
        return f"[{self.priority}] {self.title}"
