# Generated by Django 5.1.15 on 2026-05-11 08:53

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('name', models.CharField(max_length=160, verbose_name='name')),
                ('owner_tenant_schema', models.CharField(help_text='Canonical owner schema for MQTT ingest routing.', max_length=63, verbose_name='owner tenant schema')),
                ('status', models.CharField(choices=[('provisioning', 'Provisioning'), ('active', 'Active'), ('offline', 'Offline'), ('retired', 'Retired')], default='provisioning', max_length=32, verbose_name='status')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('last_seen_at', models.DateTimeField(blank=True, null=True, verbose_name='last seen at')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
            options={
                'verbose_name': 'device',
                'verbose_name_plural': 'devices',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['uuid'], name='devices_dev_uuid_634260_idx'), models.Index(fields=['owner_tenant_schema', 'status'], name='devices_dev_owner_t_0d91a3_idx')],
            },
        ),
        migrations.CreateModel(
            name='DeviceCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_key', models.CharField(max_length=255, unique=True, verbose_name='API key')),
                ('api_secret', models.CharField(max_length=255, verbose_name='API secret')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('last_used_at', models.DateTimeField(blank=True, null=True, verbose_name='last used at')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('device', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='credential', to='devices.device', verbose_name='device')),
            ],
            options={
                'verbose_name': 'device credential',
                'verbose_name_plural': 'device credentials',
            },
        ),
    ]
