# Generated by Django 5.1.15 on 2026-05-11 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='activated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='activated at'),
        ),
        migrations.AddField(
            model_name='device',
            name='provisioned_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='provisioned at'),
        ),
    ]
