# Generated by Django 5.1.15 on 2026-05-11 21:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0002_device_activated_at_device_provisioned_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceHeartbeat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('received_at', models.DateTimeField(auto_now_add=True, verbose_name='received at')),
                ('firmware_version', models.CharField(blank=True, default='', max_length=50, verbose_name='reported firmware version')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP address')),
                ('rssi', models.IntegerField(blank=True, null=True, verbose_name='WiFi RSSI')),
                ('battery_level', models.FloatField(blank=True, null=True, verbose_name='battery level')),
            ],
            options={
                'verbose_name': 'device heartbeat',
                'verbose_name_plural': 'device heartbeats',
                'ordering': ['-received_at'],
            },
        ),
        migrations.CreateModel(
            name='DeviceShadow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reported', models.JSONField(blank=True, default=dict, help_text='Last state reported by the device.', verbose_name='reported state')),
                ('desired', models.JSONField(blank=True, default=dict, help_text='State the cloud wants the device to converge to.', verbose_name='desired state')),
                ('reported_version', models.PositiveIntegerField(default=0, verbose_name='reported version')),
                ('desired_version', models.PositiveIntegerField(default=0, verbose_name='desired version')),
                ('last_reported_at', models.DateTimeField(blank=True, null=True, verbose_name='last reported at')),
                ('last_desired_at', models.DateTimeField(blank=True, null=True, verbose_name='last desired at')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
            options={
                'verbose_name': 'device shadow',
                'verbose_name_plural': 'device shadows',
            },
        ),
        migrations.RemoveField(
            model_name='devicecredential',
            name='api_secret',
        ),
        migrations.AddField(
            model_name='device',
            name='capabilities',
            field=models.JSONField(blank=True, default=list, help_text="List of device capabilities (e.g. ['temperature', 'humidity', 'soil_moisture']).", verbose_name='capabilities'),
        ),
        migrations.AddField(
            model_name='device',
            name='firmware_version',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='firmware version'),
        ),
        migrations.AddField(
            model_name='device',
            name='hardware_revision',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='hardware revision'),
        ),
        migrations.AddField(
            model_name='device',
            name='heartbeat_interval_seconds',
            field=models.PositiveIntegerField(default=60, verbose_name='heartbeat interval (s)'),
        ),
        migrations.AddField(
            model_name='device',
            name='last_ip',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='last IP address'),
        ),
        migrations.AddField(
            model_name='device',
            name='mqtt_client_id',
            field=models.CharField(blank=True, default='', max_length=160, verbose_name='MQTT client ID'),
        ),
        migrations.AddField(
            model_name='device',
            name='provisioning_status',
            field=models.CharField(choices=[('unprovisioned', 'Unprovisioned'), ('identity_created', 'Identity created'), ('certificate_issued', 'Certificate issued'), ('registered', 'Registered'), ('activated', 'Activated'), ('failed', 'Failed')], default='unprovisioned', max_length=32, verbose_name='provisioning status'),
        ),
        migrations.AddField(
            model_name='device',
            name='serial_number',
            field=models.CharField(default='', help_text='Factory-assigned hardware serial number.', max_length=120, unique=True, verbose_name='serial number'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='devicecredential',
            name='api_secret_hash',
            field=models.CharField(default='', help_text='Argon2 hash of the shared secret — never store the plaintext.', max_length=255, verbose_name='API secret hash'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='devicecredential',
            name='rotated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='rotated at'),
        ),
        migrations.AddIndex(
            model_name='device',
            index=models.Index(fields=['serial_number'], name='devices_dev_serial__4a3e3a_idx'),
        ),
        migrations.AddIndex(
            model_name='device',
            index=models.Index(fields=['mqtt_client_id'], name='devices_dev_mqtt_cl_980c34_idx'),
        ),
        migrations.AddField(
            model_name='deviceheartbeat',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='heartbeats', to='devices.device', verbose_name='device'),
        ),
        migrations.AddField(
            model_name='deviceshadow',
            name='device',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='shadow', to='devices.device', verbose_name='device'),
        ),
        migrations.AddIndex(
            model_name='deviceheartbeat',
            index=models.Index(fields=['device', '-received_at'], name='devices_dev_device__52692e_idx'),
        ),
    ]
