# Generated by Django 5.1.15 on 2026-05-11 22:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0003_deviceheartbeat_deviceshadow_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProvisioningAuditEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(max_length=32, verbose_name='from status')),
                ('to_status', models.CharField(max_length=32, verbose_name='to status')),
                ('triggered_by', models.CharField(blank=True, default='', help_text='Service, user, or system that triggered this transition.', max_length=255, verbose_name='triggered by')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='metadata')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provisioning_audit', to='devices.device', verbose_name='device')),
            ],
            options={
                'verbose_name': 'provisioning audit entry',
                'verbose_name_plural': 'provisioning audit entries',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['device', '-created_at'], name='devices_pro_device__18cd94_idx')],
            },
        ),
    ]
