# Generated by Django 5.1.15 on 2026-05-12 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0004_provisioningauditentry'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceDomainEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField(help_text='UUID4 string — matches DeviceEvent.event_id.', max_length=64, unique=True, verbose_name='event ID')),
                ('event_type', models.CharField(help_text='Canonical device.<past_tense> event type.', max_length=120, verbose_name='event type')),
                ('aggregate_type', models.CharField(default='Device', max_length=64, verbose_name='aggregate type')),
                ('aggregate_id', models.CharField(help_text='Device serial_number.', max_length=120, verbose_name='aggregate ID')),
                ('payload', models.JSONField(blank=True, default=dict, verbose_name='payload')),
                ('correlation_id', models.CharField(blank=True, default='', max_length=64, verbose_name='correlation ID')),
                ('causation_id', models.CharField(blank=True, default='', help_text='event_id of the event that caused this one.', max_length=64, verbose_name='causation ID')),
                ('tenant_schema', models.CharField(max_length=63, verbose_name='tenant schema')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
            ],
            options={
                'verbose_name': 'device domain event',
                'verbose_name_plural': 'device domain events',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['aggregate_id', '-created_at'], name='devices_dev_aggrega_021281_idx'), models.Index(fields=['event_type', '-created_at'], name='devices_dev_event_t_cf84ba_idx'), models.Index(fields=['tenant_schema', '-created_at'], name='devices_dev_tenant__ac6a37_idx'), models.Index(fields=['correlation_id'], name='devices_dev_correla_8fb548_idx')],
            },
        ),
    ]
