# Generated by Django 5.1.15 on 2026-05-11 08:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('care_engine', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160, verbose_name='name')),
                ('status', models.CharField(choices=[('active', 'Active'), ('needs_attention', 'Needs attention'), ('removed', 'Removed')], default='active', max_length=32, verbose_name='status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('species', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plants', to='care_engine.plantspecies', verbose_name='species')),
            ],
            options={
                'verbose_name': 'plant',
                'verbose_name_plural': 'plants',
                'ordering': ['name'],
            },
        ),
    ]
