# Generated by Django 5.1.15 on 2026-05-11 08:53

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IntegrationOutbox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idempotency_key', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='idempotency key')),
                ('event_type', models.CharField(max_length=120, verbose_name='event type')),
                ('aggregate_type', models.CharField(max_length=120, verbose_name='aggregate type')),
                ('aggregate_id', models.CharField(max_length=120, verbose_name='aggregate ID')),
                ('target_provider_schema', models.CharField(blank=True, max_length=63, verbose_name='target provider schema')),
                ('payload', models.JSONField(default=dict, verbose_name='payload')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('delivered', 'Delivered'), ('failed', 'Failed'), ('dead_letter', 'Dead letter')], default='pending', max_length=32, verbose_name='status')),
                ('attempts', models.PositiveIntegerField(default=0, verbose_name='attempts')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
            options={
                'verbose_name': 'integration outbox',
                'verbose_name_plural': 'integration outbox',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='integration_status_1ab0ea_idx'), models.Index(fields=['aggregate_type', 'aggregate_id'], name='integration_aggrega_26098f_idx')],
            },
        ),
        migrations.CreateModel(
            name='OutboxDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('delivered', 'Delivered'), ('failed', 'Failed'), ('dead_letter', 'Dead letter')], default='pending', max_length=32, verbose_name='status')),
                ('response_code', models.PositiveIntegerField(blank=True, null=True, verbose_name='response code')),
                ('error_message', models.TextField(blank=True, verbose_name='error message')),
                ('delivered_at', models.DateTimeField(blank=True, null=True, verbose_name='delivered at')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('outbox', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='integrations.integrationoutbox', verbose_name='outbox')),
            ],
            options={
                'verbose_name': 'outbox delivery',
                'verbose_name_plural': 'outbox deliveries',
                'ordering': ['-created_at'],
            },
        ),
    ]
