# Generated by Django 5.1.15 on 2026-05-11 09:38

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='integrationoutbox',
            name='available_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='available at'),
        ),
        migrations.AddField(
            model_name='integrationoutbox',
            name='event_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='event ID'),
        ),
        migrations.AddField(
            model_name='integrationoutbox',
            name='last_error',
            field=models.TextField(blank=True, verbose_name='last error'),
        ),
        migrations.AddField(
            model_name='integrationoutbox',
            name='processed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='processed at'),
        ),
        migrations.AddField(
            model_name='integrationoutbox',
            name='retry_count',
            field=models.PositiveIntegerField(default=0, verbose_name='retry count'),
        ),
        migrations.AlterField(
            model_name='integrationoutbox',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('processed', 'Processed'), ('retry', 'Retry'), ('dead_letter', 'Dead letter')], default='pending', max_length=32, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='outboxdelivery',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('processed', 'Processed'), ('retry', 'Retry'), ('dead_letter', 'Dead letter')], default='pending', max_length=32, verbose_name='status'),
        ),
        migrations.AddIndex(
            model_name='integrationoutbox',
            index=models.Index(fields=['event_id'], name='integration_event_i_19d3d5_idx'),
        ),
        migrations.AddIndex(
            model_name='integrationoutbox',
            index=models.Index(fields=['status', 'available_at'], name='integration_status_4d6197_idx'),
        ),
    ]
