# Generated by Django 5.1.15 on 2026-05-11 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0002_integrationoutbox_available_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='outboxdelivery',
            name='attempt_number',
            field=models.PositiveIntegerField(default=1, verbose_name='attempt number'),
        ),
        migrations.AddField(
            model_name='outboxdelivery',
            name='error',
            field=models.TextField(blank=True, verbose_name='error'),
        ),
        migrations.AddIndex(
            model_name='outboxdelivery',
            index=models.Index(fields=['outbox', 'attempt_number'], name='integration_outbox__7ba463_idx'),
        ),
        migrations.AddIndex(
            model_name='outboxdelivery',
            index=models.Index(fields=['status', 'created_at'], name='integration_status_bfa4b7_idx'),
        ),
    ]
