# Generated by Django 5.1.15 on 2026-05-11 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0003_outboxdelivery_attempt_number_outboxdelivery_error_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProviderConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider_tenant_id', models.CharField(max_length=120, verbose_name='provider tenant ID')),
                ('provider_base_url', models.URLField(verbose_name='provider base URL')),
                ('api_key_hash', models.CharField(blank=True, help_text='Placeholder for encrypted/hashed provider API credential reference.', max_length=255, verbose_name='API key hash')),
                ('status', models.CharField(choices=[('active', 'Active'), ('disabled', 'Disabled'), ('revoked', 'Revoked')], default='active', max_length=32, verbose_name='status')),
                ('scopes', models.JSONField(blank=True, default=list, verbose_name='scopes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('revoked_at', models.DateTimeField(blank=True, null=True, verbose_name='revoked at')),
            ],
            options={
                'verbose_name': 'provider connection',
                'verbose_name_plural': 'provider connections',
                'ordering': ['provider_tenant_id'],
                'indexes': [models.Index(fields=['provider_tenant_id', 'status'], name='integration_provide_0c8c38_idx')],
            },
        ),
    ]
