# Generated by Django 5.1.15 on 2026-05-11 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("integrations", "0004_providerconnection"),
    ]

    operations = [
        migrations.AddField(
            model_name="providerconnection",
            name="key_id",
            field=models.CharField(
                blank=True,
                help_text="Public identifier for HMAC signing key selection.",
                max_length=120,
                verbose_name="key ID",
            ),
        ),
        migrations.AddField(
            model_name="providerconnection",
            name="shared_secret_reference",
            field=models.CharField(
                blank=True,
                help_text="Development placeholder; replace with encrypted secret manager reference.",
                max_length=255,
                verbose_name="shared secret reference",
            ),
        ),
    ]
