# Generated by Django 5.1.15 on 2026-05-11 13:00

import django.db.models.deletion
from django.db import migrations, models
from django.db.models import Q


class Migration(migrations.Migration):

    dependencies = [
        ("integrations", "0005_providerconnection_hmac_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProviderKey",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("key_id", models.CharField(max_length=120, verbose_name="key ID")),
                (
                    "secret_reference",
                    models.CharField(
                        help_text="Reference to a secret resolver entry; never store the plain secret here.",
                        max_length=255,
                        verbose_name="secret reference",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("disabled", "Disabled"),
                            ("revoked", "Revoked"),
                            ("rotated", "Rotated"),
                        ],
                        default="active",
                        max_length=32,
                        verbose_name="status",
                    ),
                ),
                ("valid_from", models.DateTimeField(verbose_name="valid from")),
                ("valid_until", models.DateTimeField(blank=True, null=True, verbose_name="valid until")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="created at")),
                ("rotated_at", models.DateTimeField(blank=True, null=True, verbose_name="rotated at")),
                ("revoked_at", models.DateTimeField(blank=True, null=True, verbose_name="revoked at")),
                (
                    "provider_connection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="provider_keys",
                        to="integrations.providerconnection",
                        verbose_name="provider connection",
                    ),
                ),
            ],
            options={
                "verbose_name": "provider key",
                "verbose_name_plural": "provider keys",
                "ordering": ["provider_connection_id", "-created_at"],
                "indexes": [
                    models.Index(fields=["provider_connection", "status"], name="integration_provide_bd66fe_idx"),
                    models.Index(fields=["key_id", "status"], name="integration_key_id_40f3b7_idx"),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=Q(("status", "active")),
                        fields=("provider_connection",),
                        name="unique_active_provider_key_per_connection",
                    ),
                    models.UniqueConstraint(
                        condition=Q(("status", "active")),
                        fields=("key_id",),
                        name="unique_active_provider_key_id",
                    ),
                ],
            },
        ),
    ]
