# Generated by Django 5.1.15 on 2026-05-11 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0006_providerkey'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProviderEngagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_tenant_id', models.CharField(max_length=120, verbose_name='owner tenant ID')),
                ('provider_tenant_id', models.CharField(max_length=120, verbose_name='provider tenant ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('suspended', 'Suspended'), ('revoked', 'Revoked')], default='pending', max_length=32, verbose_name='status')),
                ('scopes', models.JSONField(blank=True, default=list, help_text='Allowed sync scopes for this engagement.', verbose_name='scopes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('activated_at', models.DateTimeField(blank=True, null=True, verbose_name='activated at')),
                ('suspended_at', models.DateTimeField(blank=True, null=True, verbose_name='suspended at')),
                ('revoked_at', models.DateTimeField(blank=True, null=True, verbose_name='revoked at')),
            ],
            options={
                'verbose_name': 'provider engagement',
                'verbose_name_plural': 'provider engagements',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['owner_tenant_id', 'provider_tenant_id', 'status'], name='integration_owner_t_1490c1_idx')],
                'constraints': [models.UniqueConstraint(fields=('owner_tenant_id', 'provider_tenant_id'), name='unique_owner_provider_engagement')],
            },
        ),
    ]
