# Generated by Django 5.1.15 on 2026-05-11 11:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0007_providerengagement'),
    ]

    operations = [
        migrations.CreateModel(
            name='SyncRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_type', models.CharField(choices=[('full', 'Full'), ('delta', 'Delta'), ('resync', 'Resync')], max_length=16, verbose_name='run type')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=16, verbose_name='status')),
                ('started_at', models.DateTimeField(verbose_name='started at')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='completed at')),
                ('failed_at', models.DateTimeField(blank=True, null=True, verbose_name='failed at')),
                ('error', models.TextField(blank=True, help_text='Error detail when the run failed.', null=True, verbose_name='error')),
                ('stats', models.JSONField(blank=True, default=dict, help_text="Aggregated stats e.g. {'processed': 42, 'failed': 1}.", verbose_name='stats')),
                ('engagement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_runs', to='integrations.providerengagement', verbose_name='engagement')),
            ],
            options={
                'verbose_name': 'sync run',
                'verbose_name_plural': 'sync runs',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='SyncItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField(max_length=255, verbose_name='event ID')),
                ('event_type', models.CharField(max_length=128, verbose_name='event type')),
                ('aggregate_type', models.CharField(max_length=128, verbose_name='aggregate type')),
                ('aggregate_id', models.CharField(max_length=255, verbose_name='aggregate ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processed', 'Processed'), ('failed', 'Failed'), ('skipped', 'Skipped')], default='pending', max_length=16, verbose_name='status')),
                ('error', models.TextField(blank=True, help_text='Error detail when processing failed.', null=True, verbose_name='error')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='processed at')),
                ('sync_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_items', to='integrations.syncrun', verbose_name='sync run')),
            ],
            options={
                'verbose_name': 'sync item',
                'verbose_name_plural': 'sync items',
                'ordering': ['sync_run', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='SyncCheckpoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stream_name', models.CharField(max_length=64, verbose_name='stream name')),
                ('last_event_id', models.CharField(blank=True, help_text='Outbox event UUID of the last successfully synced event.', max_length=255, null=True, verbose_name='last event ID')),
                ('last_event_created_at', models.DateTimeField(blank=True, help_text='Timestamp of the last successfully synced event.', null=True, verbose_name='last event created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('engagement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_checkpoints', to='integrations.providerengagement', verbose_name='engagement')),
                ('last_successful_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='integrations.syncrun', verbose_name='last successful run')),
            ],
            options={
                'verbose_name': 'sync checkpoint',
                'verbose_name_plural': 'sync checkpoints',
                'ordering': ['engagement', 'stream_name'],
            },
        ),
        migrations.AddIndex(
            model_name='syncrun',
            index=models.Index(fields=['engagement', 'status'], name='integration_engagem_c59f4b_idx'),
        ),
        migrations.AddIndex(
            model_name='syncrun',
            index=models.Index(fields=['engagement', '-started_at'], name='integration_engagem_06f487_idx'),
        ),
        migrations.AddIndex(
            model_name='syncitem',
            index=models.Index(fields=['sync_run', 'status'], name='integration_sync_ru_81aa38_idx'),
        ),
        migrations.AddIndex(
            model_name='syncitem',
            index=models.Index(fields=['event_id'], name='integration_event_i_9eb35a_idx'),
        ),
        migrations.AddIndex(
            model_name='synccheckpoint',
            index=models.Index(fields=['engagement', 'stream_name'], name='integration_engagem_e030f8_idx'),
        ),
        migrations.AddConstraint(
            model_name='synccheckpoint',
            constraint=models.UniqueConstraint(fields=('engagement', 'stream_name'), name='unique_sync_checkpoint_per_stream'),
        ),
    ]
