# Generated by Django 5.1.15 on 2026-05-11 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlantSpecies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160, verbose_name='name')),
                ('name_sr', models.CharField(max_length=160, null=True, verbose_name='name')),
                ('name_en', models.CharField(max_length=160, null=True, verbose_name='name')),
                ('name_hr', models.CharField(max_length=160, null=True, verbose_name='name')),
                ('name_sl', models.CharField(max_length=160, null=True, verbose_name='name')),
                ('name_mk', models.CharField(max_length=160, null=True, verbose_name='name')),
                ('name_sq', models.CharField(max_length=160, null=True, verbose_name='name')),
                ('name_el', models.CharField(max_length=160, null=True, verbose_name='name')),
                ('name_de', models.CharField(max_length=160, null=True, verbose_name='name')),
                ('slug', models.SlugField(max_length=180, unique=True, verbose_name='slug')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('description_sr', models.TextField(blank=True, null=True, verbose_name='description')),
                ('description_en', models.TextField(blank=True, null=True, verbose_name='description')),
                ('description_hr', models.TextField(blank=True, null=True, verbose_name='description')),
                ('description_sl', models.TextField(blank=True, null=True, verbose_name='description')),
                ('description_mk', models.TextField(blank=True, null=True, verbose_name='description')),
                ('description_sq', models.TextField(blank=True, null=True, verbose_name='description')),
                ('description_el', models.TextField(blank=True, null=True, verbose_name='description')),
                ('description_de', models.TextField(blank=True, null=True, verbose_name='description')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
            options={
                'verbose_name': 'plant species',
                'verbose_name_plural': 'plant species',
                'ordering': ['name'],
            },
        ),
    ]
