# Generated by Django 5.1.15 on 2026-05-12 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('care_engine', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=180, verbose_name='name')),
                ('description', models.TextField(blank=True, default='', verbose_name='description')),
                ('metric_key', models.CharField(help_text='The metric this rule evaluates (e.g. soil_moisture, temperature).', max_length=120, verbose_name='metric key')),
                ('operator', models.CharField(choices=[('gt', 'Greater than'), ('gte', 'Greater than or equal'), ('lt', 'Less than'), ('lte', 'Less than or equal'), ('eq', 'Equal'), ('neq', 'Not equal')], max_length=10, verbose_name='operator')),
                ('threshold_value', models.FloatField(verbose_name='threshold value')),
                ('severity', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('critical', 'Critical')], default='warning', max_length=20, verbose_name='severity')),
                ('enabled', models.BooleanField(default=True, verbose_name='enabled')),
                ('cooldown_seconds', models.PositiveIntegerField(default=300, help_text='Minimum interval between alert triggers. 0 = no cooldown.', verbose_name='cooldown (seconds)')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='metadata')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
            options={
                'verbose_name': 'rule',
                'verbose_name_plural': 'rules',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['metric_key', 'enabled'], name='care_engine_metric__901642_idx')],
            },
        ),
    ]
