# Generated by Django 5.1.15 on 2026-05-11 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=180, verbose_name='name')),
                ('kind', models.CharField(choices=[('site', 'Site'), ('building', 'Building'), ('room', 'Room'), ('area', 'Area'), ('service_region', 'Service region')], default='site', max_length=32, verbose_name='kind')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='address')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='latitude')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='longitude')),
                ('timezone', models.CharField(default='Europe/Belgrade', max_length=64, verbose_name='timezone')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
            options={
                'verbose_name': 'location',
                'verbose_name_plural': 'locations',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['kind'], name='locations_l_kind_0533e4_idx')],
            },
        ),
    ]
